# GET http://localhost:8080/flashcards
GET https://go-ai-eng-flashcards.onrender.com/flashcards

###
# POST http://localhost:8080/flashcards
POST https://go-ai-eng-flashcards.onrender.com/flashcards
Content-Type: application/json

{
  "content": "Test content"
}
###

DELETE http://localhost:8080/flashcards/2

###

GET https://go-ai-eng-flashcards.onrender.com/flashcards

###

POST https://go-ai-eng-flashcards.onrender.com/flashcards
Content-Type: application/json

{
  "content": "Test content"
}

###

GET https://go-ai-eng-flashcards.onrender.com/flashcards/1