# GET http://localhost:8080/flashcards
GET http://localhost:8080/flashcards

###
# POST http://localhost:8080/flashcards
POST http://localhost:8080/flashcards
Content-Type: application/json

{
  "content": "Test content"
}
###

DELETE http://localhost:8080/flashcards/2

###

GET http://localhost:8080/flashcards

###

POST http://localhost:8080/flashcards
Content-Type: application/json

{
  "content": "Test content"
}

###

GET http://localhost:8080/flashcards/1